name: Collecte Data Montpellier

on:
  schedule:
    - cron: '*/10 * * * *'  # Se lance toutes les 10 minutes
  workflow_dispatch:        # Permet de lancer manuellement si besoin

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write       # Important pour pouvoir sauvegarder le CSV
    
    steps:
      - name: Récupération du code
        uses: actions/checkout@v3

      - name: Installation Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Installation des librairies
        run: pip install requests

      - name: Lancement du script
        run: python main.py

      - name: Sauvegarde des données
        run: |
          git config --global user.name 'Bot Montpellier'
          git config --global user.email 'bot@noreply.github.com'
          git add historique_parkings.csv
          git commit -m "Auto-update : nouvelles données ajoutées" || echo "Pas de changement"
          git push
